### ISSUE TITLE
Problems with pagination

### ISSUE THREAD

**Issue by pierre-josselin** [wistefan/mintaka#84]
Hello,

My temporal query is limited to 100 results by Mintaka (206 Partial Content).

I did read the note in the [README.md](https://github.com/FIWARE/mintaka/blob/main/README.md#pagination) file about pagination.
But the "Next-Page" and "Previous-Page" headers are missing from the response:

![image](https://user-images.githubusercontent.com/70814177/156787218-034edc1e-cb63-4f4e-8ab4-532e49b56fa3.png)

And this request does not work:

`GET /temporal/entities/urn:ngsi-ld:test?pageSize=150`

```
ProblemDetails(type=https://uri.etsi.org/ngsi-ld/errors/BadRequestData, title=Unsupported parameters, status=400, detail=Received unsupported parameter(s): [pageSize], instance=null)
```

I tried that too, without success:

`GET /temporal/entities/urn:ngsi-ld:test?pageAnchor=2`

```
ProblemDetails(type=https://uri.etsi.org/ngsi-ld/errors/BadRequestData, title=Unsupported parameters, status=400, detail=Received unsupported parameter(s): [pageAnchor], instance=null)
```

`GET /temporal/entities/urn:ngsi-ld:test?limit=150`

```
ProblemDetails(type=https://uri.etsi.org/ngsi-ld/errors/BadRequestData, title=Unsupported parameters, status=400, detail=Received unsupported parameter(s): [limit], instance=null)
```

These parameters do not seem to be implemented, but it is not mentioned in the [README.md](https://github.com/FIWARE/mintaka/blob/main/README.md).
Tested with 0.5.0 and previous, deployed by docker with [the example docker-compose script](https://hub.docker.com/r/fiware/mintaka).

**Comment by wistefan** [comment]
Hello @pierre-josselin ,

one thing to notice on pagination in temporal is, that we have to paginate in two dimensions: 
1. number of entities included in the query-result
2. time-frame to be included in the result

You do get the 400 for "pageSize", "limit" and "pageAnchor" since they are only valid for limiting the number of entities to be retrieved(dimension 1). The query is on one specific entity, thus nothing can be limited here. Since you get the 206 result, your result is limited due to the second dimension of pagination. As described in the second part of 6.3.10 of the NGSI-LD Api(https://docbox.etsi.org/isg/cim/open/Latest%20release%20NGSI-LD%20API%20for%20public%20comment.pdf), the response with code 206 includes a "Content-Range" header that informs about the range that the query response was limited to. You should use that information for the next query to receive the next timeframe(e.g. use "timerel" and "timeAt" to retrieve the next timeframe ).

**Comment by pierre-josselin** [comment]
Thank you @wistefan for your answer.
